### ISSUE TITLE
Need test-unit as a gem for ruby 2.2+

### ISSUE THREAD

**Issue by farnoy** [Ink/filepicker-rails#128]
While working on my change I encountered this:

```
/data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require': Ruby 2.2+ has removed test/unit from the core library. Rails requires this as a dependency. Please add test-unit gem to your Gemfile: `gem 'test-unit', '~> 3.0'` (cannot load such file -- test/unit)" (LoadError)
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-rails-3.3.3/lib/rspec/rails/adapters.rb:52:in `<module:Rails>'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-rails-3.3.3/lib/rspec/rails/adapters.rb:7:in `<module:RSpec>'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-rails-3.3.3/lib/rspec/rails/adapters.rb:6:in `<top (required)>'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-rails-3.3.3/lib/rspec/rails.rb:5:in `<top (required)>'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
	from /data/filepicker-rails/spec/rails_helper.rb:4:in `<top (required)>'
	from /data/filepicker-rails/spec/features/rails_integration_spec.rb:1:in `require'
	from /data/filepicker-rails/spec/features/rails_integration_spec.rb:1:in `<top (required)>'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:102:in `setup'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
	from /data/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rspec-core-3.3.2/exe/rspec:4:in `<main>'
```

**Comment by maurogeorge** [comment]
Thanks for the report. Closed here https://github.com/Ink/filepicker-rails/commit/56fc27baee9744bfd45deabbcd6210caaa27c831
